import {
  i18n,
  JSX,
  ReflectionKind,
  type DefaultThemeRenderContext,
  type PageEvent,
  type Reflection,
} from "typedoc";

const h = JSX.createElement;

/**
 * TypeDoc's toolbar with the `ENGLISH·COURSE` wordmark and an `API` tag as
 * its title.
 *
 * @remarks
 * Everything except the title link is TypeDoc's own markup: `main.js` binds
 * the search dialog and the mobile menu to these exact IDs, so they must not
 * change.
 */
export function cinemaToolbar(context: DefaultThemeRenderContext): JSX.Element {
  return h(
    "header",
    { class: "tsd-page-toolbar" },
    h(
      "div",
      { class: "tsd-toolbar-contents container" },
      brandLink(context),
      navigationLinks(context),
      searchTrigger(context),
      searchDialog(),
      menuTrigger(context),
    ),
  );
}

/**
 * The page title for a declaration: breadcrumb, the declaration's kind as an
 * eyebrow, then its name alone as the `h1`.
 */
export function cinemaDeclarationHeader(
  context: DefaultThemeRenderContext,
  props: PageEvent<Reflection>,
): JSX.Element {
  const model = props.model;
  return h(
    "div",
    { class: "tsd-page-title" },
    context.breadcrumbs(model),
    h("p", { class: "cinema-eyebrow cinema-kind" }, ReflectionKind.singularString(model.kind)),
    h(
      "h1",
      { class: model.isDeprecated() ? "deprecated" : "" },
      model.name,
      typeParameterList(model),
      context.reflectionFlags(model),
    ),
  );
}

/**
 * The footer: the wordmark and the command that regenerates the reference,
 * between TypeDoc's footer hooks.
 */
export function cinemaFooter(context: DefaultThemeRenderContext): JSX.Element {
  return h(
    "footer",
    null,
    context.hook("footer.begin", context),
    h(
      "div",
      { class: "cinema-footer container" },
      wordmark(),
      h("p", null, "Generated by TypeDoc · regenerate with ", h("code", null, "pnpm run docs")),
    ),
    context.hook("footer.end", context),
  );
}

function brandLink(context: DefaultThemeRenderContext): JSX.Element {
  const href = context.options.getValue("titleLink") || context.relativeURL("index.html");
  return h(
    "a",
    { href, class: "title cinema-brand" },
    wordmark(),
    " ",
    h("span", { class: "cinema-api-tag" }, "API"),
  );
}

function wordmark(): JSX.Element {
  return h(
    "span",
    { class: "cinema-wordmark" },
    "ENGLISH",
    h("span", { class: "cinema-wordmark-dot" }, "·"),
    "COURSE",
  );
}

function navigationLinks(context: DefaultThemeRenderContext): JSX.Element {
  const links = Object.entries(context.options.getValue("navigationLinks"));
  return h(
    "div",
    { id: "tsd-toolbar-links" },
    links.map(([label, url]) => h("a", { href: url }, label)),
  );
}

function searchTrigger(context: DefaultThemeRenderContext): JSX.Element {
  return h(
    "button",
    { id: "tsd-search-trigger", class: "tsd-widget", "aria-label": i18n.theme_search() },
    context.icons.search(),
  );
}

function searchDialog(): JSX.Element {
  return h(
    "dialog",
    { id: "tsd-search", "aria-label": i18n.theme_search() },
    h("input", {
      role: "combobox",
      id: "tsd-search-input",
      "aria-controls": "tsd-search-results",
      "aria-autocomplete": "list",
      "aria-expanded": "true",
      spellcheck: false,
      autocapitalize: "off",
      autocomplete: "off",
      placeholder: i18n.theme_search_placeholder(),
      maxLength: 100,
    }),
    h("ul", { role: "listbox", id: "tsd-search-results" }),
    h(
      "div",
      { id: "tsd-search-status", "aria-live": "polite", "aria-atomic": "true" },
      h("div", null, i18n.theme_preparing_search_index()),
    ),
  );
}

function menuTrigger(context: DefaultThemeRenderContext): JSX.Element {
  return h(
    "a",
    {
      href: "#",
      class: "tsd-widget menu",
      id: "tsd-toolbar-menu-trigger",
      "data-toggle": "menu",
      "aria-label": i18n.theme_menu(),
    },
    context.icons.menu(),
  );
}

function typeParameterList(model: Reflection): string {
  const names = model.isDeclaration() ? (model.typeParameters ?? []).map((p) => p.name) : [];
  return names.length ? `<${names.join(", ")}>` : "";
}
